---
server:
  port: 8888
spring:
  security:
    user:
      name: pluralsight
      password: pluralsight
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Giancarlo2709/pluralsight-spring-cloudconfig-wa-tolls
          #username: uname
          #password: pass
          ## va y busca en el repositorio todas la carpetas que empiecen con station
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/Giancarlo2709/pluralsight-spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'
          

